### PR TITLE
Text Editor

### PR DESCRIPTION
**Pull request by TristanStreich**
# Description

Text Editor to run in browser for writing chess engines. ~Leaving as draft since I just npm installed this and then copied the files over. Feel like there is a better way to do this. Maybe just actually do npm and add a build.rs which invokes npm install 🤔~

Quickly and efficiently pulls code from cdn! 🚀 

For lua specifically the default language server is all but nonexistant but I know you can hook this up to the leading lua language server according to [this example](https://github.com/arnoson/monaco-lua-example/tree/main)

# Testing

You should give it a try

### CODE REVIEW

**Review by CarterMcClellan — COMMENTED** [review]
This is quite an impressive PR!

It looks like microsoft has already done you the favor of hosting all this code in a CDN!

```js
<script src="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/loader.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/editor/editor.main.css" rel="stylesheet" /> 
const editor = monaco.editor.create(..., {
  theme: 'vs-dark' 
});
const editor = monaco.editor.create(..., {
  language: ‘lua’
});
```

**Comment by CarterMcClellan** [comment]
pretty wild
```bash
wget https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/loader.min.js 
--2024-01-10 23:07:59--  https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/loader.min.js
Resolving cdnjs.cloudflare.com (cdnjs.cloudflare.com)... 104.17.25.14, 104.17.24.14
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.17.25.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/javascript]
Saving to: ‘loader.min.js’

loader.min.js                              [ <=>                                                                         ]  30.25K  --.-KB/s    in 0.004s  

2024-01-10 23:07:59 (7.53 MB/s) - ‘loader.min.js’ saved [30972]
```

size is not too bad
```bash
~ du -h loader.min.js 
 32K	loader.min.js
```

**Comment by CarterMcClellan** [comment]
and the css

```bash
(base) ➜  ~ wget https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/editor/editor.main.css
--2024-01-10 23:09:19--  https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.23.0/min/vs/editor/editor.main.css
Resolving cdnjs.cloudflare.com (cdnjs.cloudflare.com)... 104.17.25.14, 104.17.24.14
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.17.25.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/css]
Saving to: ‘editor.main.css’

editor.main.css                            [ <=>                                                                         ]  68.14K  --.-KB/s    in 0.002s  

2024-01-10 23:09:19 (33.4 MB/s) - ‘editor.main.css’ saved [69777]

(base) ➜  ~ du -h editor.main.css                                                                         
 72K	editor.main.css
```

**Comment by TristanStreich** [comment]
I wonder what it looks like if we pull the `dev` version rather than the `min` version

**Comment by TristanStreich** [comment]
Screenshot 2024-01-10 at 11 12 34 PM
Interesting!

**Comment by CarterMcClellan** [comment]
believe min refers to this: https://www.cloudflare.com/learning/performance/why-minify-javascript-code/#:~:text=Minification%2C%20also%20known%20as%20minimization,shorter%20variable%20names%20and%20functions.

So likely reducing the size of the files our users are downloading.

Suspect dev in the other version

**Comment by TristanStreich** [comment]
Right, I'm curious how much smaller min is than the fully expanded version. But trying arbitrary variations of the cdn url is so far proving unfruitful

**Comment by CarterMcClellan** [comment]
Ah, I don't see any hosted here: https://cdnjs.com/libraries/monaco-editor

**Review by CarterMcClellan — APPROVED** [review]

**Comment by CarterMcClellan** [comment]
Awesome stuff!

**Comment by CarterMcClellan** [comment]
Seems like crates which allow us to run lua in rust would be useful 🤔

**Pull request merged**
