### PR TITLE
Tristan/player vs bot

### PR DESCRIPTION
**Pull request by TristanStreich**
# Description
First draft of player vs bot. Plays against random engine.

# Test
Played a few games against the bot. (Playing this bot is actively destroying my elo)
Things that I have tried
- en passant
- castling
- capturing
- promoting (auto promote to queen for now)
- also regular piece moving ofc

Most of the above "just works" thanks to the rust backend crate doing most of the heavy lifting

### CODE REVIEW

**Comment by TristanStreich** [comment]
oh wait, i literaly just found you already have a player_vs_bot.html. Don't know how I didn't see this


took me a while to find those event listeners and you already had them.... 🤦

**Comment by CarterMcClellan** [comment]
Nice!

**Comment by CarterMcClellan** [comment]
using a little UCI notation instead of FEN, I dig it

**Comment by CarterMcClellan** [comment]
Ran into a bug when testing it
Screenshot 2024-01-09 at 10 39 32 AM
in this position I seem to be unable to play Queen or Bishop g5.

The server is panicking on  src/player_vs_bot.rs:25:14

**Comment by CarterMcClellan** [comment]
The bishop move is checkmate, so I think one issue is that we may be panicking when the list of bot moves is none

**Comment by CarterMcClellan** [comment]
But the Queen move is not checkmate, so I am not sure what the error is there, 
the FEN is 
```bash
1nbb4/r2pk3/1npp4/p5Q1/3P4/8/PPP1PPPP/RNB1KB1R b - - 1 1
```

here is the lichess link if you just wanna load from there: https://lichess.org/analysis/1nbb2Q1/r2pk3/1npp4/p7/3P4/8/PPP1PPPP/RNB1KB1R_w_-_-_0_1?color=white#0

**Comment by CarterMcClellan** [comment]
I think what happened it I played the bishop move first which was recorded in the game here

https://github.com/CarterMcClellan/Rustiator/blob/24d6e8d4cbea9524a2a8b1ced4be8e726942305f/src/player_vs_bot.rs#L20

Then the two boards (in the client and on the server) got out of sync somehow. Something has to be wonky with this line

https://github.com/CarterMcClellan/Rustiator/blob/24d6e8d4cbea9524a2a8b1ced4be8e726942305f/client/game.html#L63

Because the move Bishop g5 never updated the board in my browser.

Edit: It did register, but only after I refreshed the tab 🤔

Edit Edit: Oooooh its because like we said before the server already registered the move, so by refreshing the page, we trigger another render from the backend which simply sends back the latest registered board state

**Comment by CarterMcClellan** [comment]
I think most of these were solved with these changes: https://github.com/CarterMcClellan/Rustiator/pull/12

**Review by CarterMcClellan — APPROVED** [review]

**Comment by TristanStreich** [comment]
the fact that refreshing the tab works is kinda fun. Did not purposefully design that endpoint to work that way but it is nice that it just works out 😂

**Pull request merged**
